
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package lexerAndParser;

/** CUP generated class containing symbol constants. */
public class WorldParserSym {
  /* terminals */
  public static final int LKEY = 37;
  public static final int WORLDS = 39;
  public static final int UNDEFINEDCOLOR = 12;
  public static final int ENTERO = 41;
  public static final int TARGETS = 23;
  public static final int LPAREN = 27;
  public static final int LCORCH = 35;
  public static final int ROWS = 3;
  public static final int MINUS = 30;
  public static final int CONFIG = 6;
  public static final int RPAREN = 28;
  public static final int RCORCH = 36;
  public static final int POINTS = 25;
  public static final int TYPE = 22;
  public static final int BOARD = 18;
  public static final int COMMA = 26;
  public static final int DIV = 32;
  public static final int BOXCES = 9;
  public static final int HALL = 14;
  public static final int PLUS = 29;
  public static final int BOXCPOS = 8;
  public static final int EOF = 0;
  public static final int BRICK = 15;
  public static final int PLAYER = 24;
  public static final int RKEY = 38;
  public static final int PLAYERCOLOR = 13;
  public static final int BOXC = 7;
  public static final int error = 1;
  public static final int WORLD = 40;
  public static final int NAME = 2;
  public static final int ERROR = 33;
  public static final int COLOR = 16;
  public static final int POSY = 19;
  public static final int TIMES = 31;
  public static final int POSX = 20;
  public static final int COLS = 4;
  public static final int BOXES = 21;
  public static final int HALLCOLOR = 11;
  public static final int BRICKCOLOR = 10;
  public static final int ALL = 5;
  public static final int AP = 34;
  public static final int NAMEW = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NAME",
  "ROWS",
  "COLS",
  "ALL",
  "CONFIG",
  "BOXC",
  "BOXCPOS",
  "BOXCES",
  "BRICKCOLOR",
  "HALLCOLOR",
  "UNDEFINEDCOLOR",
  "PLAYERCOLOR",
  "HALL",
  "BRICK",
  "COLOR",
  "NAMEW",
  "BOARD",
  "POSY",
  "POSX",
  "BOXES",
  "TYPE",
  "TARGETS",
  "PLAYER",
  "POINTS",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "ERROR",
  "AP",
  "LCORCH",
  "RCORCH",
  "LKEY",
  "RKEY",
  "WORLDS",
  "WORLD",
  "ENTERO"
  };
}

