// DO NOT EDIT
// Generated by JFlex 1.9.0 http://jflex.de/
// source: /home/dou2023/AndroidStudioProjects/Proyecto1Compi1_2023/resources/wold.jflex

package lexerAndParser;

import static lexerAndParser.WorldParserSym.*;
import java_cup.runtime.*;


@SuppressWarnings("fallthrough")
public class WorldLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\u10cf\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\1\1\3\22\0\1\1\1\0"+
    "\1\4\1\5\4\0\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\12\16\1\17\6\0\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\23\1\26\1\27\1\23"+
    "\1\30\1\31\2\23\1\32\2\23\1\33\5\23\1\34"+
    "\1\35\1\23\1\36\1\0\1\37\1\0\1\40\1\0"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\52\1\61\1\62\1\63\1\64\1\52\1\65\1\66"+
    "\1\67\1\52\1\70\1\0\1\71\7\0\1\1\32\0"+
    "\1\1\u01df\0\1\1\177\0\13\1\35\0\2\1\5\0"+
    "\1\1\57\0\1\1\240\0\1\1\377\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\4\1"+
    "\1\16\1\17\13\1\1\20\1\21\1\22\26\0\1\23"+
    "\1\24\16\23\1\0\1\25\1\0\1\26\1\23\1\0"+
    "\2\23\1\27\2\23\1\30\1\23\1\31\1\32\1\33"+
    "\1\23\1\34\2\23\1\35\1\36\1\37\2\0\1\40"+
    "\2\23\1\0\3\23\1\41\3\0\1\42\1\0\1\43"+
    "\2\23\1\44\6\0\1\45\1\23\6\0\1\23\1\46"+
    "\5\0\1\23\2\0\1\47\4\0\1\50\4\0\1\51"+
    "\1\52\6\0\1\53\3\0\1\54";

  private static int [] zzUnpackAction() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\72\0\164\0\72\0\256\0\72\0\72"+
    "\0\72\0\72\0\72\0\72\0\72\0\72\0\350\0\72"+
    "\0\u0122\0\u015c\0\u0196\0\u01d0\0\72\0\72\0\u020a\0\u0244"+
    "\0\u027e\0\u02b8\0\u02f2\0\u032c\0\u0366\0\u03a0\0\u03da\0\u0414"+
    "\0\u044e\0\72\0\72\0\256\0\u0488\0\u04c2\0\u04fc\0\u0536"+
    "\0\u0570\0\u05aa\0\u05e4\0\u061e\0\u0658\0\u0692\0\u06cc\0\u0706"+
    "\0\u0740\0\u077a\0\u07b4\0\u07ee\0\u0828\0\u0862\0\u089c\0\u08d6"+
    "\0\u0910\0\u094a\0\u0570\0\u0570\0\u0984\0\u09be\0\u09f8\0\u0a32"+
    "\0\u0a6c\0\u0aa6\0\u0ae0\0\u0b1a\0\u0b54\0\u0b8e\0\u0bc8\0\u0c02"+
    "\0\u0c3c\0\u0c76\0\u0cb0\0\72\0\u0cea\0\72\0\u0d24\0\u0d5e"+
    "\0\u0d98\0\u0dd2\0\u0570\0\u0e0c\0\u0e46\0\u0570\0\u0e80\0\u0570"+
    "\0\u0570\0\u0570\0\u0eba\0\u0570\0\u0ef4\0\u0f2e\0\72\0\72"+
    "\0\u0570\0\u0f68\0\u0fa2\0\u0570\0\u0fdc\0\u1016\0\u1050\0\u108a"+
    "\0\u10c4\0\u10fe\0\u1138\0\u1172\0\u11ac\0\u11e6\0\u0570\0\u1220"+
    "\0\u125a\0\u1294\0\u12ce\0\u0570\0\u1308\0\u1342\0\u137c\0\u13b6"+
    "\0\u13f0\0\u142a\0\u0570\0\u1464\0\u149e\0\u14d8\0\u1512\0\u154c"+
    "\0\u1586\0\u15c0\0\u15fa\0\72\0\u1634\0\u166e\0\u16a8\0\u16e2"+
    "\0\u171c\0\u1756\0\u1790\0\u17ca\0\72\0\u1804\0\u183e\0\u1878"+
    "\0\u18b2\0\72\0\u18ec\0\u1926\0\u1960\0\u199a\0\72\0\72"+
    "\0\u19d4\0\u1a0e\0\u1a48\0\u1a82\0\u1abc\0\u1af6\0\72\0\u1b30"+
    "\0\u1b6a\0\u1ba4\0\72";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\2"+
    "\1\21\1\22\2\2\1\23\1\24\7\2\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\4\27\1\33\5\27\1\34"+
    "\1\27\1\35\1\36\1\27\1\37\1\40\1\41\2\27"+
    "\1\42\1\43\74\0\1\3\105\0\1\44\22\0\27\44"+
    "\20\0\1\17\106\0\1\45\62\0\1\46\76\0\1\47"+
    "\60\0\1\50\71\0\16\51\3\0\27\51\22\0\16\51"+
    "\3\0\13\51\1\52\13\51\22\0\16\51\3\0\16\51"+
    "\1\53\1\51\1\54\6\51\22\0\16\51\3\0\16\51"+
    "\1\55\10\51\22\0\16\51\3\0\1\56\26\51\22\0"+
    "\16\51\3\0\1\57\26\51\22\0\16\51\3\0\13\51"+
    "\1\60\2\51\1\61\10\51\22\0\16\51\3\0\16\51"+
    "\1\62\10\51\22\0\16\51\3\0\1\63\25\51\1\64"+
    "\22\0\16\51\3\0\15\51\1\65\11\51\22\0\16\51"+
    "\3\0\16\51\1\66\10\51\31\0\1\67\71\0\1\70"+
    "\74\0\1\71\70\0\1\72\56\0\1\73\1\0\16\73"+
    "\3\0\27\73\20\0\1\73\1\0\16\73\3\0\13\73"+
    "\1\74\13\73\20\0\1\73\1\0\16\73\3\0\1\75"+
    "\24\73\1\76\1\73\20\0\1\73\1\0\16\73\3\0"+
    "\10\73\1\77\16\73\20\0\1\73\1\0\16\73\3\0"+
    "\13\73\1\100\1\73\1\101\11\73\20\0\1\73\1\0"+
    "\16\73\3\0\13\73\1\102\13\73\20\0\1\73\1\0"+
    "\16\73\3\0\14\73\1\103\12\73\20\0\1\73\1\0"+
    "\16\73\3\0\1\104\26\73\20\0\1\73\1\0\16\73"+
    "\3\0\21\73\1\105\5\73\20\0\1\73\1\0\16\73"+
    "\3\0\24\73\1\106\2\73\20\0\1\73\1\0\16\73"+
    "\3\0\20\73\1\107\6\73\20\0\1\73\1\0\16\73"+
    "\3\0\17\73\1\110\7\73\20\0\1\73\1\0\16\73"+
    "\3\0\3\73\1\111\23\73\20\0\1\73\1\0\16\73"+
    "\3\0\20\73\1\112\6\73\24\0\1\113\100\0\1\114"+
    "\72\0\1\115\70\0\1\116\56\0\1\73\1\0\16\73"+
    "\3\0\20\73\1\117\6\73\20\0\1\73\1\0\16\73"+
    "\2\0\1\120\4\73\1\121\22\73\20\0\1\73\1\0"+
    "\16\73\3\0\2\73\1\122\24\73\20\0\1\73\1\0"+
    "\16\73\3\0\21\73\1\123\5\73\20\0\1\73\1\0"+
    "\16\73\3\0\5\73\1\124\21\73\20\0\1\73\1\0"+
    "\16\73\3\0\13\73\1\125\13\73\20\0\1\73\1\0"+
    "\16\73\3\0\4\73\1\126\22\73\20\0\1\73\1\0"+
    "\16\73\3\0\26\73\1\127\20\0\1\73\1\0\14\73"+
    "\1\130\1\131\3\0\27\73\20\0\1\73\1\0\16\73"+
    "\3\0\21\73\1\132\5\73\20\0\1\73\1\0\16\73"+
    "\3\0\6\73\1\133\20\73\20\0\1\73\1\0\16\73"+
    "\3\0\4\73\1\134\22\73\20\0\1\73\1\0\16\73"+
    "\3\0\4\73\1\135\22\73\20\0\1\73\1\0\16\73"+
    "\3\0\13\73\1\136\13\73\32\0\1\137\74\0\1\140"+
    "\54\0\1\73\1\0\16\73\3\0\3\73\1\141\23\73"+
    "\45\0\1\142\13\0\1\143\30\0\1\73\1\0\16\73"+
    "\3\0\21\73\1\144\5\73\20\0\1\73\1\0\16\73"+
    "\3\0\12\73\1\145\14\73\20\0\1\73\1\0\16\73"+
    "\3\0\10\73\1\146\16\73\20\0\1\73\1\0\16\73"+
    "\2\0\1\147\27\73\20\0\1\73\1\0\16\73\3\0"+
    "\4\73\1\150\22\73\20\0\1\73\1\0\16\73\3\0"+
    "\4\73\1\151\22\73\20\0\1\73\1\0\16\73\3\0"+
    "\5\73\1\152\21\73\20\0\1\73\1\0\16\73\3\0"+
    "\3\73\1\153\23\73\61\0\1\154\70\0\1\155\31\0"+
    "\1\73\1\0\16\73\2\0\1\156\27\73\20\0\1\73"+
    "\1\0\16\73\3\0\6\73\1\157\20\73\45\0\1\160"+
    "\44\0\1\73\1\0\16\73\3\0\20\73\1\161\6\73"+
    "\20\0\1\73\1\0\16\73\3\0\22\73\1\162\4\73"+
    "\20\0\1\73\1\0\16\73\3\0\10\73\1\163\16\73"+
    "\20\0\1\73\1\0\16\73\3\0\21\73\1\164\5\73"+
    "\56\0\1\165\55\0\1\166\74\0\1\167\105\0\1\170"+
    "\30\0\1\73\1\0\16\73\2\0\1\171\27\73\20\0"+
    "\1\73\1\0\16\73\2\0\1\172\21\73\1\173\5\73"+
    "\20\0\1\73\1\0\16\73\3\0\15\73\1\174\11\73"+
    "\61\0\1\175\75\0\1\176\65\0\1\177\66\0\1\200"+
    "\60\0\1\201\71\0\1\202\44\0\1\73\1\0\16\73"+
    "\3\0\4\73\1\203\22\73\63\0\1\204\51\0\1\205"+
    "\104\0\1\206\74\0\1\207\71\0\1\210\71\0\1\211"+
    "\30\0\1\73\1\0\16\73\3\0\3\73\1\212\23\73"+
    "\63\0\1\213\67\0\1\214\73\0\1\215\64\0\1\216"+
    "\71\0\1\217\33\0\1\73\1\0\16\73\2\0\1\220"+
    "\27\73\51\0\1\221\103\0\1\222\67\0\1\223\71\0"+
    "\1\224\55\0\1\225\73\0\1\226\105\0\1\227\71\0"+
    "\1\230\67\0\1\231\75\0\1\232\62\0\1\233\55\0"+
    "\1\234\110\0\1\235\55\0\1\236\107\0\1\237\67\0"+
    "\1\240\66\0\1\241\74\0\1\242\73\0\1\243\10\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[7134];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\1\11\1\1\10\11\1\1\1\11"+
    "\4\1\2\11\13\1\2\11\1\1\26\0\20\1\1\0"+
    "\1\11\1\0\1\11\1\1\1\0\16\1\2\11\1\1"+
    "\2\0\3\1\1\0\4\1\3\0\1\1\1\0\4\1"+
    "\6\0\2\1\6\0\1\1\1\11\5\0\1\1\2\0"+
    "\1\11\4\0\1\11\4\0\2\11\6\0\1\11\3\0"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

	private Symbol symbol(int type) {
		return new Symbol(type, yyline + 1, yycolumn + 1);
	}

	private Symbol symbol(int type, Object value) {
		//System.out.println("lexer: "+String.valueOf(value));
		return new Symbol(type, yyline + 1, yycolumn + 1, value);
	}
	private void imprimir(String text){
		System.out.println("lexer: "+text);
	}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public WorldLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return symbol(ERROR, yytext());
            }
          // fall through
          case 45: break;
          case 2:
            { /* Ignore */
            }
          // fall through
          case 46: break;
          case 3:
            { return symbol(AP, yytext());
            }
          // fall through
          case 47: break;
          case 4:
            { return symbol( LPAREN, yytext());
            }
          // fall through
          case 48: break;
          case 5:
            { return symbol( RPAREN, yytext());
            }
          // fall through
          case 49: break;
          case 6:
            { return symbol( TIMES, yytext());
            }
          // fall through
          case 50: break;
          case 7:
            { return symbol( PLUS, yytext());
            }
          // fall through
          case 51: break;
          case 8:
            { return symbol( COMMA, yytext());
            }
          // fall through
          case 52: break;
          case 9:
            { return symbol( MINUS, yytext());
            }
          // fall through
          case 53: break;
          case 10:
            { return symbol( POINT, yytext());
            }
          // fall through
          case 54: break;
          case 11:
            { return symbol( DIV, yytext());
            }
          // fall through
          case 55: break;
          case 12:
            { //imprimir(yytext());
						return new Symbol(ENTERO, yyline + 1, yycolumn + 1, Integer.valueOf(yytext()));
            }
          // fall through
          case 56: break;
          case 13:
            { return symbol( POINTS, yytext());
            }
          // fall through
          case 57: break;
          case 14:
            { return symbol(LCORCH, yytext());
            }
          // fall through
          case 58: break;
          case 15:
            { return symbol(RCORCH, yytext());
            }
          // fall through
          case 59: break;
          case 16:
            { return symbol(LKEY, yytext());
            }
          // fall through
          case 60: break;
          case 17:
            { return symbol(RKEY, yytext());
            }
          // fall through
          case 61: break;
          case 18:
            { //imprimir(String.valueOf(yytext()));
						return new Symbol(COLOR,yyline+1,yycolumn+1, String.valueOf( yytext()) );
            }
          // fall through
          case 62: break;
          case 19:
            { //imprimir(String.valueOf(yytext()));	
						return new Symbol(NAMEW, yyline+1,yycolumn+1, String.valueOf( yytext() ) );
            }
          // fall through
          case 63: break;
          case 20:
            { return symbol(ALL, yytext());
            }
          // fall through
          case 64: break;
          case 21:
            { return symbol( CEIL, yytext());
            }
          // fall through
          case 65: break;
          case 22:
            { return symbol(HALL, yytext());
            }
          // fall through
          case 66: break;
          case 23:
            { return symbol(COLS, yytext());
            }
          // fall through
          case 67: break;
          case 24:
            { return symbol(NAME, yytext());
            }
          // fall through
          case 68: break;
          case 25:
            { return symbol(POSX, yytext());
            }
          // fall through
          case 69: break;
          case 26:
            { return symbol(POSY, yytext());
            }
          // fall through
          case 70: break;
          case 27:
            { return symbol(ROWS, yytext());
            }
          // fall through
          case 71: break;
          case 28:
            { return symbol(TYPE, yytext());
            }
          // fall through
          case 72: break;
          case 29:
            { return symbol(BRICK, yytext());
            }
          // fall through
          case 73: break;
          case 30:
            { return symbol( FLOOR, yytext());
            }
          // fall through
          case 74: break;
          case 31:
            { return symbol(BOARD, yytext());
            }
          // fall through
          case 75: break;
          case 32:
            { return symbol(BOXES, yytext());
            }
          // fall through
          case 76: break;
          case 33:
            { return symbol(WORLD, yytext());
            }
          // fall through
          case 77: break;
          case 34:
            { return symbol(CONFIG, yytext());
            }
          // fall through
          case 78: break;
          case 35:
            { return symbol(PLAYER, yytext());
            }
          // fall through
          case 79: break;
          case 36:
            { return symbol(WORLDS,yytext());
            }
          // fall through
          case 80: break;
          case 37:
            { return symbol(TARGETS, yytext());
            }
          // fall through
          case 81: break;
          case 38:
            { return symbol(BOXC, yytext());
            }
          // fall through
          case 82: break;
          case 39:
            { return symbol(HALLCOLOR, yytext());
            }
          // fall through
          case 83: break;
          case 40:
            { return symbol(BRICKCOLOR, yytext());
            }
          // fall through
          case 84: break;
          case 41:
            { return symbol(PLAYERCOLOR, yytext());
            }
          // fall through
          case 85: break;
          case 42:
            { return symbol(BOXCES, yytext());
            }
          // fall through
          case 86: break;
          case 43:
            { return symbol(UNDEFINEDCOLOR, yytext());
            }
          // fall through
          case 87: break;
          case 44:
            { return symbol(BOXCPOS, yytext());
            }
          // fall through
          case 88: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
