
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package lexerAndParser;

/** CUP generated class containing symbol constants. */
public class WorldParserXMLSym {
  /* terminals */
  public static final int NAMEW = 22;
  public static final int BOXC = 12;
  public static final int BOXCES = 14;
  public static final int PLAYERCOLOR = 18;
  public static final int PLAYER = 29;
  public static final int WORLD = 6;
  public static final int ERROR = 30;
  public static final int COLOR = 21;
  public static final int NAME = 8;
  public static final int I = 5;
  public static final int BOXCPOS = 13;
  public static final int TYPE = 27;
  public static final int TARGETS = 28;
  public static final int BRICK = 20;
  public static final int EOF = 0;
  public static final int INICIAL = 2;
  public static final int HALLCOLOR = 16;
  public static final int UNDEFINEDCOLOR = 17;
  public static final int CIERRE = 4;
  public static final int FINAL = 3;
  public static final int error = 1;
  public static final int ROWS = 9;
  public static final int COLS = 10;
  public static final int ENTERO = 31;
  public static final int BOXES = 26;
  public static final int BOARD = 23;
  public static final int HALL = 19;
  public static final int WORLDS = 7;
  public static final int BRICKCOLOR = 15;
  public static final int POSY = 24;
  public static final int CONFIG = 11;
  public static final int POSX = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIAL",
  "FINAL",
  "CIERRE",
  "I",
  "WORLD",
  "WORLDS",
  "NAME",
  "ROWS",
  "COLS",
  "CONFIG",
  "BOXC",
  "BOXCPOS",
  "BOXCES",
  "BRICKCOLOR",
  "HALLCOLOR",
  "UNDEFINEDCOLOR",
  "PLAYERCOLOR",
  "HALL",
  "BRICK",
  "COLOR",
  "NAMEW",
  "BOARD",
  "POSY",
  "POSX",
  "BOXES",
  "TYPE",
  "TARGETS",
  "PLAYER",
  "ERROR",
  "ENTERO"
  };
}

